name: YouTube Bot Automation

on:
  workflow_dispatch:

jobs:
  youtube-bot:
    runs-on: windows-latest
    strategy:
      matrix:
        account:
          - "JilliBeckzuf57890h@vasim.org|Hello9999"
          - "LilyanVaughanrbl36662o@vasim.org|Hello9999"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          pip install easyocr


      - name: Install dependencies
        run: |
          pip install pyautogui pillow opencv-python-headless requests

      - name: Run YouTube Bot
        run: |
          python main.py "${{ matrix.account }}"
